"""Figure 4 Step=100: Per-residue helix recovery — plotting only.

Reads CSVs from logs/figure4_step100/ (generated by fig4_step100_production.py).
Produces: figure4.png/pdf, figure4_supp.png/pdf → figure_s4.png/pdf.

Style: Arial 16/18 pt, 600 DPI, colorblind-safe palette, top/right spines off.
Panel labels omitted (added in manuscript layout).
"""
import os, sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

PROJECT = '/MDdata/data04/jxhuang/cg_cascade'
OUT = os.path.join(PROJECT, 'logs/figure4_step100')

plt.rcParams.update({
    'font.family':        'sans-serif',
    'font.sans-serif':    ['Arial', 'Helvetica', 'DejaVu Sans'],
    'font.size':          16,
    'axes.labelsize':     18,
    'axes.titlesize':     18,
    'xtick.labelsize':    14,
    'ytick.labelsize':    14,
    'legend.fontsize':    14,
    'axes.linewidth':     0.8,
    'xtick.major.width':  0.8,
    'ytick.major.width':  0.8,
    'xtick.direction':    'out',
    'ytick.direction':    'out',
    'figure.dpi':         600,
    'savefig.dpi':        600,
    'axes.spines.top':    False,
    'axes.spines.right':  False,
    'legend.frameon':     False,
    'mathtext.default':   'regular',
})

# Colorblind-safe palette (Wong, 2011) — consistent with Figures 2 & 3
C_REF    = '#0072B2'   # Blue — Reference
C_PRED   = '#D55E00'   # Vermilion — Predicted
C_NEUTRAL = '#999999'  # Grey — highlights / reference lines
C_STEP5  = '#3775BA'   # Blue secondary — Step=5
C_STEP100 = '#E28E2C'  # Gold — Step=100


def style_ax(ax):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)


def load_data():
    df_all = pd.read_csv(os.path.join(OUT, 'per_residue_helix.csv'))
    df_summary = pd.read_csv(os.path.join(OUT, 'per_system_summary.csv'))
    p15paf_z = pd.read_csv(os.path.join(OUT, 'p15PAF_zoom.csv'))
    actr_z = pd.read_csv(os.path.join(OUT, 'ACTR_zoom.csv'))
    ped184_z = pd.read_csv(os.path.join(OUT, 'PED00184_zoom.csv'))
    return df_all, df_summary, p15paf_z, actr_z, ped184_z


# ═══════════════════════════════════════════════════════════════════════════════════
#  Main figure: 5 per-residue helix profiles (vertical stack)
# ═══════════════════════════════════════════════════════════════════════════════════

def plot_main_figure(df_all, df_summary):
    ref_order = df_summary.sort_values('ref_mean_helix_pct', ascending=False)['system'].tolist()
    n_sys = len(ref_order)
    fig, axes = plt.subplots(n_sys, 1, figsize=(12, 4 * n_sys), sharex=False)
    fig.subplots_adjust(hspace=0.5)

    for pi, ref_name in enumerate(ref_order):
        ax = axes[pi]
        sub = df_all[df_all['system'] == ref_name]
        x = sub['residue_index'].values
        pred = sub['pred_helix'].values * 100
        ref_val = sub['ref_helix'].values * 100

        has_ref = not np.all(np.isnan(ref_val))
        if has_ref:
            ax.fill_between(x, 0, ref_val, color=C_REF, alpha=0.18, label='Reference')
            ax.plot(x, ref_val, '-', color=C_REF, linewidth=1.2)
            ymax = max(np.nanmax(ref_val) * 1.35, 15.0)
        else:
            ymax = 15.0
        ax.plot(x, pred, '-', color=C_PRED, linewidth=1.2, label='Predicted')

        # Zoom region indicators omitted (cleaner layout)

        sr = df_summary[df_summary['system'] == ref_name]
        if len(sr) > 0:
            r_val = sr.iloc[0]['pearson_r']
            label_str = sr.iloc[0]['label']
            label = f'{ref_name} ({label_str})'
            if not np.isnan(r_val):
                label += f', $r$ = {r_val:.2f}'
            ax.text(0.985, 0.88, label, transform=ax.transAxes, ha='right', fontsize=12,
                    bbox=dict(boxstyle='round,pad=0.25', facecolor='white', alpha=0.85,
                              edgecolor=C_NEUTRAL, lw=0.4))

        ax.set_ylim(-0.5, ymax)
        ax.set_ylabel('Helix (%)')
        style_ax(ax)
        if pi == 0:
            ax.legend(fontsize=14, loc='upper left', frameon=False)
        if pi == len(ref_order) - 1:
            ax.set_xlabel('Residue index')

    fig.tight_layout()
    fig.savefig(os.path.join(OUT, 'figure4.png'), bbox_inches='tight')
    fig.savefig(os.path.join(OUT, 'figure4.pdf'), bbox_inches='tight')
    plt.close(fig)
    print('  figure4.png / figure4.pdf saved')


# ═══════════════════════════════════════════════════════════════════════════════════
#  Panel B: p15PAF residues 54–60 zoom
# ═══════════════════════════════════════════════════════════════════════════════════

def plot_panel_b(p15paf_z):
    fig, ax = plt.subplots(figsize=(9, 6))
    if len(p15paf_z) > 0:
        x_pos = p15paf_z['residue_index'].values
        ref_vals = p15paf_z['ref_helix'].values * 100
        pred_vals = p15paf_z['pred_helix'].values * 100
        w = 0.35
        ax.bar(x_pos - w/2, ref_vals, w, color=C_REF, alpha=0.9, label='Reference',
               edgecolor='white', lw=0.3)
        ax.bar(x_pos + w/2, pred_vals, w, color=C_PRED, alpha=0.9, label='Predicted',
               edgecolor='white', lw=0.3)
        if 59 in x_pos:
            idx59 = np.where(x_pos == 59)[0][0]
            ax.annotate('TRP 59\n17.6% ref', xy=(59, ref_vals[idx59]),
                        xytext=(59.5, ref_vals[idx59] + 3),
                        fontsize=10, ha='left',
                        arrowprops=dict(arrowstyle='->', color='black'))
    ax.set_xlabel('Residue index')
    ax.set_ylabel('Helix fraction (%)')
    ax.set_ylim(0, 22)
    ax.set_xticks(range(54, 61))
    ax.legend(fontsize=14, loc='upper left')
    style_ax(ax)
    fig.tight_layout()
    fig.savefig(os.path.join(OUT, 'figure4_panelB.png'), bbox_inches='tight')
    fig.savefig(os.path.join(OUT, 'figure4_panelB.pdf'), bbox_inches='tight')
    plt.close(fig)
    print('  figure4_panelB.png / figure4_panelB.pdf saved')


# ═══════════════════════════════════════════════════════════════════════════════════
#  Supplementary figure: 2×2 grid
#    A: Tif2 NRID zoom  |  B: ACTR N-terminal zoom
#    C: p15PAF zoom     |  D: Step=5 vs Step=100 comparison
# ═══════════════════════════════════════════════════════════════════════════════════

def plot_supplementary(df_summary, ped184_z, actr_z, p15paf_z):
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))

    # A: PED00184 residue 120-140 region zoom
    ax = axes[0, 0]
    if len(ped184_z) > 0:
        x_pos = ped184_z['residue_index'].values
        ref_vals = ped184_z['ref_helix'].values * 100
        pred_vals = ped184_z['pred_helix'].values * 100
        w = 0.35
        ax.bar(x_pos - w/2, ref_vals, w, color=C_REF, alpha=0.9, label='Reference',
               edgecolor='white', lw=0.3)
        ax.bar(x_pos + w/2, pred_vals, w, color=C_PRED, alpha=0.9, label='Predicted',
               edgecolor='white', lw=0.3)
    ax.set_xlabel('Residue index')
    ax.set_ylabel('Helix (%)')
    ax.set_title('PED00184 (Tif2 NRID) residues 120–140', fontsize=14, fontweight='bold')
    ax.legend(fontsize=12, loc='upper right')
    style_ax(ax)

    # B: ACTR N-terminal helix region zoom
    ax = axes[0, 1]
    if len(actr_z) > 0:
        x_pos = actr_z['residue_index'].values
        ref_vals = actr_z['ref_helix'].values * 100
        pred_vals = actr_z['pred_helix'].values * 100
        w = 0.35
        ax.bar(x_pos - w/2, ref_vals, w, color=C_REF, alpha=0.9, label='Reference',
               edgecolor='white', lw=0.3)
        ax.bar(x_pos + w/2, pred_vals, w, color=C_PRED, alpha=0.9, label='Predicted',
               edgecolor='white', lw=0.3)
    ax.set_xlabel('Residue index')
    ax.set_ylabel('Helix (%)')
    ax.set_title('PED00536 (ACTR) N-terminal helix', fontsize=14, fontweight='bold')
    ax.legend(fontsize=12, loc='upper left')
    style_ax(ax)

    # C: p15PAF residues 54-60 zoom
    ax = axes[1, 0]
    if len(p15paf_z) > 0:
        x_pos = p15paf_z['residue_index'].values
        ref_vals = p15paf_z['ref_helix'].values * 100
        pred_vals = p15paf_z['pred_helix'].values * 100
        w = 0.35
        ax.bar(x_pos - w/2, ref_vals, w, color=C_REF, alpha=0.9, label='Reference',
               edgecolor='white', lw=0.3)
        ax.bar(x_pos + w/2, pred_vals, w, color=C_PRED, alpha=0.9, label='Predicted',
               edgecolor='white', lw=0.3)
        if 59 in x_pos:
            idx59 = np.where(x_pos == 59)[0][0]
            ax.annotate('TRP 59\n17.6% ref', xy=(59, ref_vals[idx59]),
                        xytext=(59.5, ref_vals[idx59] + 3),
                        fontsize=10, ha='left',
                        arrowprops=dict(arrowstyle='->', color='black'))
    ax.set_xlabel('Residue index')
    ax.set_ylabel('Helix fraction (%)')
    ax.set_title('p15PAF (PED00016) residues 54–60', fontsize=14, fontweight='bold')
    ax.set_ylim(0, 22)
    ax.set_xticks(range(54, 61))
    ax.legend(fontsize=12, loc='upper left')
    style_ax(ax)

    # D: Step=5 vs step=100 mean helix bar chart
    ax = axes[1, 1]
    systems = df_summary['system'].values
    step5_vals = df_summary['step5_pred_mean_helix_pct'].values
    step100_vals = df_summary['pred_mean_helix_pct'].values
    x_pos = np.arange(len(systems))
    w = 0.35
    ax.bar(x_pos - w/2, step5_vals, w, color=C_STEP5, alpha=0.9,
           label='Step = 5', edgecolor='white', lw=0.3)
    ax.bar(x_pos + w/2, step100_vals, w, color=C_STEP100, alpha=0.9,
           label='Step = 100', edgecolor='white', lw=0.3)
    ax.set_xticks(x_pos)
    ax.set_xticklabels(systems, rotation=0, ha='center', fontsize=10)
    ax.set_ylabel('Mean predicted helix (%)')
    ax.legend(fontsize=12, loc='upper right')
    style_ax(ax)

    fig.tight_layout()
    fig.savefig(os.path.join(OUT, 'figure_s4.png'), bbox_inches='tight')
    fig.savefig(os.path.join(OUT, 'figure_s4.pdf'), bbox_inches='tight')
    plt.close(fig)
    print('  figure_s4.png / figure_s4.pdf saved')


# ═══════════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    print('=' * 60)
    print('  Figure 4 Step=100 Plot')
    print('=' * 60)

    df_all, df_summary, p15paf_z, actr_z, ped184_z = load_data()
    print(f'  Data: {len(df_all)} per-residue rows, {len(df_summary)} systems')

    plot_main_figure(df_all, df_summary)
    plot_supplementary(df_summary, ped184_z, actr_z, p15paf_z)

    print('\n  Plot complete.')
